name: roman_converter

services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    container_name: roman_converter
    command: ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "${PORT}"]
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT}:${PORT}"
